public class OMS_Constants {
    // Order Statuses
    public static final String ORDER_STATUS_DRAFT = 'Draft';
    public static final String ORDER_STATUS_COMPLETED = 'Completed';
    public static final String ORDER_STATUS_CANCELLED = 'Cancelled';
    // Categories
    public static final String CATEGORY_ELECTRONICS = 'Electronics';
    public static final String CATEGORY_CLOTHING = 'Clothing';
    public static final String CATEGORY_HOME = 'Home';
    public static final String CATEGORY_OTHER = 'Other';
    
    // Error Messages
    public static final String ERROR_INSUFFICIENT_STOCK = 'Insufficient stock for product: ';
    public static final String ERROR_PRODUCT_NOT_FOUND = 'Product not found.';
}